language: generic

services:
  - docker

env:
  global:
    secure: ezIHwIuBOYgc2p5i7cipffk6RFjzgUmHrYYB6mSbqYVoUD2w+6cqn4+E7X3YUzVm/AY0vo+ncf9jdRJRqXO7n/ffDpdQuy+ZA/ub6nKAf//ujVZ15gZBBogGSuwbuaHQVFywuDaoxsXKaOnoeLo9VwhIwbVD9JVb81zqj3rBPQqO+xHzTFQpHtHT9iGJ/8s5hSUNbBowOoqibGzsh33EZDLNL11aNFODZadddnxVA7ABaYZoXe8YHWsI4cqQSYsbcZhqIZIOt/XngOG8XoC/hnCdC4pIl7tMOP9litwYh6sSKkRdcxZ/LZBxorQIZXrNYy1q+4Jqpj3hEabROiSBr+ahze/LQ3CaewZclZCInhPcYMVeIOGJ1D9ozqLg827jRnyOaMbOILguiJu9+H4xHg+NeyObiROmJfJDrUEvSaY35VzoRgy4u6sv5S8A7r3Pt/Dl1rmIMDS6XTXTMg7E05jfOouKg8Cib+Bmb7lhG70ntV8cWO00GnaNqHrjXQsQOeXDAQRzIcxMPplymB4KMNizqH5hSjQKNEC8MFe2/HL0kKfDiOfdNcRAJvCJKT+EdvtFb3+j2NM1K6aHMcQ1DYcx3GSCwjX6Hm+/RzZ0Fj5q4fcUTFrSWNa908AvtTIqoKYEMGLj9FVPdR7ZvM9aXOd6NRjcPxkhtB2PpORgrc4=

script:
- docker build -t kama93/robots:latest .
- docker images
- echo "$DOCKER_TOKEN" | docker login -u kama93 --password-stdin
- docker push kama93/robots:latest
